### ISSUE TITLE
see if seahash is faster than meowhash

### ISSUE THREAD

**Issue by BrianHicks** [roc-lang/rbt#20]
Just a note for later, as I've just learned about seahash: https://lib.rs/crates/seahash

**Comment by rtfeldman** [comment]
https://news.ycombinator.com/item?id=29038813 suggests xxhash3 is worth looking into too!

**Comment by BrianHicks** [comment]
closing as we're now using blake3 for content, but need a different input hasher (which is a new issue, https://github.com/roc-lang/rbt/issues/38)
