### ISSUE TITLE
empty out environment

### ISSUE THREAD

**Issue by BrianHicks** [roc-lang/rbt#63]
we currently inherit environment variables from the parent process. We need to do that!

This should be a pretty reasonable first issue for someone, except for the fact that a lot of tools will get annoyed at you if you don't set some environment variables. The most common one I've seen is `HOME` (which we're setting in #62) but I tested a few things out and it seems like it might be necessary to set `LOCALE` to some fake value as well.

**Comment by celsobonutti** [comment]
I'd like to tackle this one 👀

**Comment by BrianHicks** [comment]
now that you've commented, it lets me assign you 😆

One thing I forgot: there's a light dependency on #62 here, but we can get around it for now by just isolating everything *but* `$HOME` (or setting `$HOME` to a truly fake value; not even a tempdir.)
